services:
  #alpine:
  #  image: alpine
  #  command: tail -F anything
  #  networks:
  #    office:

  router:
    image: gabibbo97/lidite-openwrt
    volumes:
      - ./router_config/bgpd.conf:/etc/quagga/bgpd.conf
      - ./router_config/network:/etc/uci-defaults/50_chassis_network
      - ./router_config/firewall:/etc/uci-defaults/60_chassis_firewall
      - ./router_config/firewall.user:/etc/firewall.user
    privileged: true
    environment:
      PASSWORD_DEFAULT: admin123
    networks:
      office:
        ipv4_address: 172.29.0.1
      internet:
        ipv4_address: 172.30.0.2

networks:
  office:
    internal: true
    name: office
    driver: macvlan
    ipam:
      config:
        - subnet: 172.29.0.0/24
  
  internet:
    name: internet
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24