services:
  web:
    build: web
    restart: always
    ports:
      - 5000:5000
    networks:
      net:
        ipv4_address: 172.29.0.5

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      net:
        ipv4_address: 172.29.0.6

networks:
  net:
    external: false
    name: net
    ipam:
      config:
        - subnet: 172.29.0.0/24
          gateway: 172.29.0.1