services:
  web:
    build: web
    restart: always
    ports:
      - 5000:5000
    networks:
      net:
        ipv4_address: 172.29.0.5

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/db-data:/var/lib/mysql
    networks:
      net:
        ipv4_address: 172.29.0.6
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      net:
        ipv4_address: 172.29.0.7

networks:
  net:
    external: false
    name: net
    ipam:
      config:
        - subnet: 172.29.0.0/24
          gateway: 172.29.0.1