services:
  # alpine:
  #   image: alpine
  #   depends_on: ["router"]
  #   cap_add:
  #     - NET_ADMIN
  #   entrypoint: sh -c "
  #     ip route del default; \
  #     ip route add default via 172.29.0.1 && \
  #     tail -f /dev/null"
  #   networks:
  #     office:
  #       ipv4_address: 172.29.0.2

  router:
    image: gabibbo97/lidite-openwrt
    volumes:
      - ./router_config/bgpd.conf:/etc/quagga/bgpd.conf
      - ./router_config/init.sh:/etc/uci-defaults/init.sh
      - ./router_config/firewall:/etc/config/firewall
      - ./router_config/network:/etc/config/network
      - ./router_config/firewall.user:/etc/firewall.user
    privileged: true
    environment:
      PASSWORD_DEFAULT: admin123
    networks:
      office:
        ipv4_address: 172.29.0.1
      internet:
        ipv4_address: 172.30.0.2

networks:
  office:
    name: office
    driver: bridge
    driver_opts:
      com.docker.network.bridge.gateway_mode_ipv4: isolated
    internal: true
    ipam:
      config:
        - subnet: 172.29.0.0/24

  internet:
    name: internet
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1