services:
  web:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    develop:
      watch:
        - action: sync+restart
          path: src
          target: /LearningDocker/src

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080