!
hostname router
password admin123
!
router bgp 65535
 bgp router-id 172.30.0.2
 redistribute connected
 redistribute static
 neighbor 172.30.0.1 remote-as 65534
 neighbor 172.30.0.1 route-map RejectBogons out
 neighbor 172.30.0.1 default-originate
!
 address-family ipv6
 exit-address-family
 exit
!
access-list vty permit 127.0.0.0/8
access-list vty deny any
!
ip prefix-list RFC1918PREFIXES seq 10 permit 172.29.0.0/24 le 32
!
route-map RejectBogons deny 10
 match ip address prefix-list RFC1918PREFIXES
!
route-map RejectBogons permit 65535
!
line vty
 access-class vty
!
end